// <auto-generated />
namespace Harbor.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class PageTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PageTables));
        
        string IMigrationMetadata.Id
        {
            get { return "201209301642092_PageTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
