// <auto-generated />
namespace Harbor.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class FileIDToGuid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FileIDToGuid));
        
        string IMigrationMetadata.Id
        {
            get { return "201212112036362_FileIDToGuid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
