// <auto-generated />
namespace Harbor.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class FileRelations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FileRelations));
        
        string IMigrationMetadata.Id
        {
            get { return "201211162134307_FileRelations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
