// <auto-generated />
namespace Harbor.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class NullablePayPalTaxAndShipping : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NullablePayPalTaxAndShipping));
        
        string IMigrationMetadata.Id
        {
            get { return "201311061808318_NullablePayPalTaxAndShipping"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
