// <auto-generated />
namespace Harbor.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class NavLinks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NavLinks));
        
        string IMigrationMetadata.Id
        {
            get { return "201305131316589_NavLinks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
