// <auto-generated />
namespace Harbor.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class PageLayout : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PageLayout));
        
        string IMigrationMetadata.Id
        {
            get { return "201404061413005_PageLayout"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
